version: '3.6'
services:
  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    links:
      - mysql

  client:
    container_name: client
    build:
      context: ./todo-list-app
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:4200"

  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: todo
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    volumes:
       - ./:/docker-entrypoint-initdb.d
    ports:
       - "3306:3306"