version: '1'
services:
  api:
    container_name: "api"
    build:
      context: "./api"
      dockerfile: "Dockerfile"
    restart: "always"
    ports:
      - "127.0.0.1:3000:3000"
    links:
      - "mysql"

  client:
    container_name: "todo-list-app"
    build:
      context: "./todo-list-app"
      dockerfile: "Dockerfile"
    restart: "always"
    ports:
      - "127.0.0.1:80:4200"

  mysql:
    container_name: "mysql"
    image: "mysql:5.7"
    restart: "always"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "todo
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "root"
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
    ports:
       - "127.0.0.1:3306:3306"