version: '3'
services:
  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    links:
      - mysql

  client:
    container_name: client
    build:
      context: ./todo-list-app
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:4200"

  mysql:
    container_name: mysql
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    ports:
       - "3306:3306"